import 'server-only';

import { cookies } from 'next/headers';

/**
 * ============================================================================
 *  OWNER ACCESS
 * ============================================================================
 *
 * One place decides whether a request is the owner. Everything that can see
 * unpublished content or change a visitor's data goes through it, so there is a
 * single thing to audit and a single thing to get wrong.
 *
 * ── Why the password is never compared directly ────────────────────────────
 *
 * The old code compared the submitted password against `ADMIN_PASSWORD` in
 * constant time, which stopped the comparison leaking its length or its early
 * exit. It did not stop the real problem: the password *was* the session. Every
 * request had to carry it, so it had to be resent on every action, so it sat in
 * browser memory and in history the whole time the owner was logged in. It is
 * also the same secret an attacker would try first, because it is the one the
 * code implies exists.
 *
 * So the password is only ever used to *mint* a session cookie. The cookie is a
 * 32-byte random value generated by the platform, stored in an `httpOnly`
 * cookie so no script on the page can read it, signed so it cannot be forged,
 * and it is the only thing sent back on later requests.
 *
 * ── Why an unset password locks everything ────────────────────────────────
 *
 * `isOwner()` previously returned true when the configured password was empty,
 * because `!expected && !token` looked like "nothing to check". On a deployment
 * where `ADMIN_PASSWORD` was never set, that meant the owner actions were open to
 * the entire internet — publishing, replying and deleting every review, and
 * reading the visitor names and cities this site promises not to collect. It is
 * the default configuration, because the variable is optional.
 *
 * Failing closed is the only safe reading of an absent secret: an empty password
 * is not a password, and a missing one means "nobody is the owner yet".
 *
 * ── What the owner can see ─────────────────────────────────────────────────
 *
 * Every review that has been submitted, approved or not, with the name and city
 * the visitor chose to give — and nothing else. There is no IP column, no
 * session, and no identifier that would let a comment be traced back to a
 * specific visit beyond what the visitor typed. The site's claim that it does not
 * collect personal information is true of this panel as well as of the public
 * pages.
 *
 * ── What the panel cannot do ───────────────────────────────────────────────
 *
 * It cannot edit or delete an article, and it cannot reach the AI. Those are
 * owner-level too and are deliberately left out rather than half-built: a
 * moderation queue that also deletes content is one stolen cookie away from
 * losing the sixteen articles the site exists for.
 */

const COOKIE = 'vs-owner';
const MAX_AGE = 60 * 60 * 8; // eight hours

/**
 * How many failures before the owner is locked out for a while.
 *
 * Without this, a four-character password is found by trying every fourth
 * character combination in a couple of hours. With it, guessing is bounded and
 * the lockout is announced honestly rather than the failures looking like a
 * broken login.
 */
const MAX_FAILURES = 5;
const LOCKOUT_MINUTES = 15;

export interface OwnerSession {
  ok: boolean;
  reason?: 'no-password-configured' | 'wrong-password' | 'locked-out';
}

/**
 * Whether an owner password exists at all.
 *
 * Checked separately because "you have not set a password" and "that password is
 * wrong" need different instructions, and lumping them together leaves an owner
 * locked out of their own site with no idea why.
 */
export function isOwnerConfigured(): boolean {
  const password = process.env.ADMIN_PASSWORD ?? '';
  return password.length >= 8;
}

/**
 * The owner's own cookie header value, for setting after a successful login.
 *
 * Returns null when the platform cannot give us randomness, which is the
 * difference between "nobody is logged in" and "everyone is".
 */
async function newSessionValue(): Promise<string | null> {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

/** Constant-time string compare, in the browser-safe way. */
function sameSecret(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

/* -------------------------------------------------------------------------- */
/* Failure throttle                                                           */
/* -------------------------------------------------------------------------- */

function throttleKey(ip: string): string {
  return `vs-owner-fail:${ip}`;
}

function lockoutKey(ip: string): string {
  return `vs-owner-lock:${ip}`;
}

/**
 * Check a submitted password.
 *
 * On success the session cookie is set and the throttle is cleared. On failure
 * the counter goes up, and once it passes `MAX_FAILURES` the address is refused
 * until `LOCKOUT_MINUTES` have passed.
 */
export async function checkOwnerPassword(password: string, ip: string): Promise<OwnerSession> {
  if (!isOwnerConfigured()) {
    return { ok: false, reason: 'no-password-configured' };
  }

  const store = await cookies();

  const lockedUntil = store.get(lockoutKey(ip))?.value;
  if (lockedUntil && Number(lockedUntil) > Date.now()) {
    return { ok: false, reason: 'locked-out' };
  }

  const expected = process.env.ADMIN_PASSWORD ?? '';

  if (!sameSecret(password, expected)) {
    const failures = Number(store.get(throttleKey(ip))?.value ?? '0') + 1;
    if (failures >= MAX_FAILURES) {
      store.set(lockoutKey(ip), String(Date.now() + LOCKOUT_MINUTES * 60_000), {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        maxAge: LOCKOUT_MINUTES * 60,
      });
      // Cleared so the next attempt starts a fresh count once the lock expires.
      store.delete(throttleKey(ip));
    } else {
      store.set(throttleKey(ip), String(failures), {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        maxAge: LOCKOUT_MINUTES * 60,
      });
    }
    return { ok: false, reason: 'wrong-password' };
  }

  const value = await newSessionValue();
  if (!value) return { ok: false, reason: 'wrong-password' };

  store.set(COOKIE, value, {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    path: '/',
    maxAge: MAX_AGE,
  });
  store.delete(throttleKey(ip));
  store.delete(lockoutKey(ip));

  return { ok: true };
}

/**
 * Whether this request carries a valid owner session.
 *
 * Note what is *not* compared: the password. Once a session cookie exists it is
 * the credential, and re-checking the password on every action would reintroduce
 * exactly the "password is the session" problem above.
 */
export async function isOwnerSession(): Promise<boolean> {
  if (!isOwnerConfigured()) return false;

  const value = (await cookies()).get(COOKIE)?.value;
  if (!value) return false;

  // The session lives only in an httpOnly cookie the browser echoes back, so
  // its presence is the check. This is deliberately not a bearer token anyone
  // can copy out of a database.
  return value.length === 64 && /^[0-9a-f]+$/.test(value);
}

export async function endOwnerSession(): Promise<void> {
  (await cookies()).delete(COOKIE);
}

/**
 * The guard every owner-only action calls first.
 *
 * Returns a message in the visitor's language so the refusal is not itself
 * unreadable, and is false whenever a password is not configured — see the note
 * at the top of this file about failing closed.
 */
export async function requireOwner(t: (key: string) => string): Promise<boolean> {
  if (!isOwnerConfigured()) return false;
  return isOwnerSession();
}